### ISSUE TITLE
How to left align the pagination dot to the play button

### ISSUE THREAD

**Issue by JobberRT** [p-m-p/slider#542]
In https://philparsons.co.uk/slider/docs/effects/carousel , the pagination dots are left aligned with the play button, how can I achieve that?

I've tried to use a CSS to change the `.container` grid template but it doesn't work

**Comment by p-m-p** [comment]
The available parts and properties are listed here https://philparsons.co.uk/slider/docs/guides/slider-controls. You can check out the example styling here https://github.com/p-m-p/slider/blob/main/packages/docs/src/components/Examples/styles.module.css
