### ISSUE TITLE
[BUG] Slider doesn't update slides in React

### ISSUE THREAD

**Issue by JobberRT** [p-m-p/slider#543]
https://github.com/p-m-p/slider/blob/d4ce09cc6f786ef355c69df111c5b4e80ace512e/packages/slider/src/box-slider.ts#L281

`Slider` only check children on init, which means if components are passed in props and needs to dynamic updating, `Slider` cannot get the current children count and throw `slide index error`

```typescript
This works because only render the Slider when props.pages.length > 0
			{props.pages.length > 0 &&
				<SliderControls>
					<CarouselSlider autoScroll loop pauseOnHover>
						{...props.pages}
					</CarouselSlider>
				</SliderControls>
			}

			This won't work even if props.pages are updated and length > 0
			<SliderControls>
				<CarouselSlider autoScroll loop pauseOnHover>
					{...props.pages}
				</CarouselSlider>
			</SliderControls>
```

**Comment by p-m-p** [comment]
I think that's fine as a solution but I will take a look into this because the components also don't update if a slide is added or removed.

**Comment by p-m-p** [comment]
@JobberRT can you please give the latest package a try `@boxslider/react@latest`. 

Should hopefully now find that it has no issue with updates to the slide content, I created this example to demonstrate https://stackblitz.com/edit/vitejs-vite-jnedho?file=src%2FApp.tsx.

Thanks for raising 👍🏻

**Comment by JobberRT** [comment]
@p-m-p That works perfect! Thanks for quick fix!
