### ISSUE TITLE
How to use the Side Effects option Fade Cube Tile

### ISSUE THREAD

**Issue by changmen1** [p-m-p/slider#685]
How to use the Silde Effects option Fade Cube Tile Why is there not even a code example? How do users know how to use it? I'm speechless. I've been looking for a long time but can't find how to use it. It's outrageous. Is it difficult to write a complete code?

**Comment by p-m-p** [comment]
Usage is documented here https://philparsons.co.uk/slider/docs/getting-started/usage with links to the full documentation for each package. This is also in the project README file.
